language: node_js
node_js:
- '6'
install:
- npm install smild@~4.10.1 -g
- npm install
script:
- smild build
deploy:
  skip_cleanup: true
  provider: npm
  email: sysadmin@tierratelematics.com
  api_key:
    secure: YkJrWcfHr6h+J9GJdOMjHJ9duYTMe8HvVR8SU0Fr7TmtKaakKcISiqlbt79ugzUOi1kzt7JIXaGP27eb5MIO3mqPeb9Y3KkVyXs7qeQKL694YMJ6t1qP1Jo7SCda7lCR9+9VQRc1eIxLO/N58g+2cGk4yv/UckHFVPDKp1Gzu6mANlicr8HQ63ugzuihFR3CLdMLX8PrhabY3EMweYptwtNqdDbuZT/nuv5h4vZOtcH1s5R6tmW1NoEPqWj4PA1cqHXCUK+DZFUCV3g/Ev8KP8tO3yNOTnP4HO56tihJVn74ZQTVbUtN2QfVAfNdX8cgf/PfL/w+jESECUiDJleBGFUJSwoc6Os/wo6mPJfnPqb4U8rQAZ+8/poSFpdxh2oXY5Uu2KeR2DaVwgcp9z8AeIKu/JhRLRlkRuWmOiL4+fDVORs54MtX8BdfVmwgDDRWwAAXFrA9/I4gcRAtchdy4klmLdH0GuvcT79zTFcecMfGo9fiVhYu6S3kVqL21lHNPWRQbwIFhPvwG8tSXrlVQEHi3drxCFmh5PDUjZAfgnHJypebPd5h7nzHmAs/m5y/b1ih4XwkN/wjr+44fOzFWCadZxbNKHRw4VY+TqjxgjwtDhUnvUB1QbHaeqCSs8lYCK+lQv5Y2tiix4qfNPHYgHX3/i7cyVGc3tCRGiHZGk4=
  on:
    repo: tierratelematics/goats
    tags: true
